name: Build and deploy to dev

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  buildAndDeploy2Dev:
    name: "Build and Deploy to dev"
    runs-on: self-hosted
    env:
      ENV: "dev"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_REPO_PAT }}
          submodules: recursive
      - name: Fix git config
        run: |
          git submodule foreach 'git config --global url."https://x-access-token:${{ secrets.MY_REPO_PAT }}@github.com/cmtt-ru/heyka-sdk".insteadOf "https://github.com/cmtt-ru/heyka-sdk"'
      - name: Cleanup
        uses: werf/actions/cleanup@master
        with:
          group: 1.1
          channel: alpha
        env:
          WERF_STAGES_STORAGE: "docker.pkg.github.com/cmtt-ru/${{ github.event.repository.name }}/stages-${{ github.event.repository.name }}"
          WERF_GIT_HISTORY_BASED_CLEANUP_v1_2: "1"
      - name: werf converge
        uses: werf/actions/converge@master
        with:
          group: 1.1
          channel: alpha
          env: ${{ env.ENV }}
        env:
          WERF_STAGES_STORAGE: "docker.pkg.github.com/cmtt-ru/${{ github.event.repository.name }}/stages-${{ github.event.repository.name }}"