name: Build and deploy to stage

on:
  push:
    branches:
    - stage

jobs:
  buildAndDeploy2Stage:
    name: "Build and Deploy to stage"
    runs-on: self-hosted
    env:
      ENV: "stage"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.MY_REPO_PAT }}
          submodules: recursive
      - name: Fix git config
        run: |
          git submodule foreach 'git config --global url."https://x-access-token:${{ secrets.MY_REPO_PAT }}@github.com/cmtt-ru/heyka-sdk".insteadOf "https://github.com/cmtt-ru/heyka-sdk"'
      - name: werf converge
        uses: werf/actions/converge@v1.1
        with:
          channel: alpha
          env: ${{ env.ENV }}
        env:
          WERF_STAGES_STORAGE: "ghcr.io/cmtt-ru/stages-${{ github.event.repository.name }}"
          WERF_IMAGES_REPO: "ghcr.io/cmtt-ru/${{ github.event.repository.name }}"
