name: Build and deploy to dev AWS
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  buildAndDeploy2Dev:
    name: "Build and Deploy to dev"
    runs-on: self-hosted
    env:
      WERF_KUBE_CONTEXT: "main-aws"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.MY_REPO_PAT }}
        submodules: recursive
    - name: Fix git config
      run: |
        git submodule foreach 'git config --global url."https://x-access-token:${{ secrets.MY_REPO_PAT }}@github.com/cmtt-ru/heyka-sdk".insteadOf "https://github.com/cmtt-ru/heyka-sdk"'
    - name: werf converge
      uses: werf/actions/converge@v1.2
      with:
        channel: alpha
        env: dev
