name: Cleanup Docker registry
on:
  schedule:
    - cron:  '15 * * * *'
  repository_dispatch:
    types: [cleanup]

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Cleanup
        uses: werf/actions/cleanup@master
        with:
          group: 1.1
          channel: alpha
        env:
          WERF_STAGES_STORAGE: "docker.pkg.github.com/cmtt-ru/${{ github.event.repository.name }}/stages-${{ github.event.repository.name }}"
          WERF_GIT_HISTORY_BASED_CLEANUP_v1_2: "1"
