name: cleanup
on:
  schedule:
    - cron:  '30 1 * * *'
jobs:
  cleanup:
    name: "Build and deploy backup repo"
    runs-on: self-hosted
    env:
      WERF_KUBE_CONTEXT: "main-aws"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: werf cleanup
      uses: werf/actions/cleanup@v1.2
      with:
        channel: alpha
        github-token: ${{ secrets.CLEANUP_TOKEN }}
