# name: Cleanup Docker registry
# on:
#   schedule:
#     - cron:  '45 * * * *'
#   repository_dispatch:
#     types: [cleanup]

# jobs:
#   cleanup:
#     name: Cleanup
#     runs-on: self-hosted
#     steps:

#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0

#       - name: Cleanup
#         uses: werf/actions/cleanup@v1.1
#         with:
#           channel: alpha
#         env:
#           WERF_STAGES_STORAGE: "ghcr.io/cmtt-ru/stages-heyka-web"
#           WERF_GIT_HISTORY_BASED_CLEANUP_v1_2: "1"
